{
    "openapi": "3.0.1",
    "info": {
        "title": "Payments Options",
        "description": "API for Payments Options",
        "version": "v1"
    },
    "servers": [
        {
            "url": "https://api.uat.platform.pagopa.it/odp/service/v1"
        },
        {
            "url": "https://uat.checkout.pagopa.it/odp/service/v1"
        },
        {
            "url": "https://uat.payment-wallet.pagopa.it/odp/service/v1"
        },
        {
            "url": "https://api.prf.platform.pagopa.it/odp/service/v1"
        }
    ],
    "paths": {
        "/info": {
            "get": {
                "tags": [
                    "Generic"
                ],
                "summary": "Info",
                "description": "Info",
                "operationId": "get-info",
                "responses": {
                    "200": {
                        "description": "OK",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/AppInfo"
                                },
                                "example": {
                                    "name": "string",
                                    "version": "string",
                                    "environment": "string"
                                }
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "content": {
                            "application/json": {}
                        }
                    }
                }
            }
        },
        "/payment-options/organizations/{organization-fiscal-code}/notices/{notice-number}": {
            "get": {
                "tags": [
                    "Payment Options"
                ],
                "summary": "Get payment options",
                "description": "Retrieve the payment options related to the provided input",
                "operationId": "getPaymentOptions",
                "parameters": [
                    {
                        "name": "notice-number",
                        "in": "path",
                        "description": "Notice number",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    },
                    {
                        "name": "organization-fiscal-code",
                        "in": "path",
                        "description": "Organization fiscal code",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    },
                    {
                        "name": "idPsp",
                        "in": "query",
                        "description": "PSP identifier",
                        "schema": {
                            "type": "string"
                        }
                    },
                    {
                        "name": "X-Session-Id",
                        "in": "header",
                        "schema": {
                            "type": "string"
                        }
                    }
                ],
                "responses": {
                    "400": {
                        "description": "Bad Request",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/ErrorResponse"
                                },
                                "example": {
                                    "httpStatusCode": 400,
                                    "httpStatusDescription": "Bad Request",
                                    "appErrorCode": "ODP-<ERR_ID>",
                                    "timestamp": 1724425035,
                                    "dateTime": "2024-08-23T02:57:15.0000000+00:00",
                                    "errorMessage": "Invalid request. Please check the submitted data and try again."
                                }
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized"
                    },
                    "403": {
                        "description": "Forbidden"
                    },
                    "404": {
                        "description": "Default app exception for status 404",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/ErrorResponse"
                                },
                                "example": {
                                    "httpStatusCode": 404,
                                    "httpStatusDescription": "Not Found",
                                    "appErrorCode": "ODP-<ERR_ID>",
                                    "timestamp": 1724425035,
                                    "dateTime": "2024-08-23T02:57:15.0000000+00:00",
                                    "errorMessage": "Resource not found. Please verify the request and try again."
                                }
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/ErrorResponse"
                                },
                                "example": {
                                    "httpStatusCode": 500,
                                    "httpStatusDescription": "Internal Server Error",
                                    "appErrorCode": "ODP-<ERR_ID>",
                                    "timestamp": 1724425035,
                                    "dateTime": "2024-08-23T02:57:15.0000000+00:00",
                                    "errorMessage": "An unexpected error has occurred. Please contact support."
                                }
                            }
                        }
                    },
                    "502": {
                        "description": "Bad Gateway",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/ErrorResponse"
                                },
                                "example": {
                                    "httpStatusCode": 502,
                                    "httpStatusDescription": "Bad Gateway",
                                    "appErrorCode": "ODP-23>",
                                    "timestamp": 1724425035,
                                    "dateTime": "2024-08-23T02:57:15.0000000+00:00",
                                    "errorMessage": "ODP_ERRORE_EMESSO_DA_PAA PAA_SINTASSI Error generated by PA."
                                }
                            }
                        }
                    },
                    "200": {
                        "description": "Success",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/PaymentOptionsResponse"
                                },
                                "example": {
                                    "organizationFiscalCode": "77777777777",
                                    "companyName": "EC",
                                    "officeName": "EC",
                                    "paymentOptions": [
                                        {
                                            "description": "Test PayOpt - unica opzione",
                                            "numberOfInstallments": 1,
                                            "amount": 120,
                                            "dueDate": "2024-10-30T11:59:59.0000000+00:00",
                                            "validFrom": "2024-09-30T11:59:59.0000000+00:00",
                                            "status": "non pagato",
                                            "status reason": "desc",
                                            "allCCP": "false",
                                            "installments": [
                                                {
                                                    "nav": "311111111111111111",
                                                    "iuv": "311111111111111111",
                                                    "amount": 120,
                                                    "description": "Test Opt Inst - unica opzione",
                                                    "dueDate": "2024-10-30T11:59:59.0000000+00:00",
                                                    "validFrom": "2024-09-30T11:59:59.0000000+00:00",
                                                    "status": "non pagato",
                                                    "status reason": "desc"
                                                }
                                            ]
                                        }
                                    ]
                                }
                            }
                        }
                    }
                }
            }
        }
    },
    "components": {
        "schemas": {
            "AppInfo": {
                "type": "object",
                "properties": {
                    "name": {
                        "type": "string"
                    },
                    "version": {
                        "type": "string"
                    },
                    "environment": {
                        "type": "string"
                    }
                }
            },
            "ErrorResponse": {
                "type": "object",
                "properties": {
                    "httpStatusCode": {
                        "type": "integer",
                        "format": "int32"
                    },
                    "httpStatusDescription": {
                        "type": "string"
                    },
                    "errorMessage": {
                        "type": "string"
                    },
                    "appErrorCode": {
                        "type": "string"
                    },
                    "timestamp": {
                        "type": "integer",
                        "format": "int64"
                    },
                    "dateTime": {
                        "type": "string"
                    }
                }
            },
            "Installment": {
                "type": "object",
                "properties": {
                    "nav": {
                        "type": "string"
                    },
                    "iuv": {
                        "type": "string"
                    },
                    "amount": {
                        "type": "integer",
                        "format": "int64"
                    },
                    "description": {
                        "type": "string"
                    },
                    "dueDate": {
                        "type": "string"
                    },
                    "validFrom": {
                        "type": "string"
                    },
                    "status": {
                        "$ref": "#/components/schemas/InstallmentEnum"
                    },
                    "statusReason": {
                        "type": "string"
                    }
                }
            },
            "InstallmentEnum": {
                "enum": [
                    "POI_UNPAID",
                    "POI_PAID",
                    "POI_EXPIRED_NOT_PAYABLE",
                    "POI_EXPIRED_UNPAID",
                    "POI_INVALID"
                ],
                "type": "string"
            },
            "PaymentOption": {
                "type": "object",
                "properties": {
                    "description": {
                        "type": "string"
                    },
                    "numberOfInstallments": {
                        "type": "integer",
                        "format": "int32"
                    },
                    "dueDate": {
                        "type": "string"
                    },
                    "validFrom": {
                        "type": "string"
                    },
                    "amount": {
                        "type": "integer",
                        "format": "int64"
                    },
                    "status": {
                        "$ref": "#/components/schemas/PaymentOptionStatusEnum"
                    },
                    "statusReason": {
                        "type": "string"
                    },
                    "allCCP": {
                        "type": "boolean"
                    },
                    "installments": {
                        "type": "array",
                        "items": {
                            "$ref": "#/components/schemas/Installment"
                        }
                    }
                }
            },
            "PaymentOptionStatusEnum": {
                "enum": [
                    "PO_UNPAID",
                    "PO_PAID",
                    "PO_PARTIALLY_PAID",
                    "PO_EXPIRED_NOT_PAYABLE",
                    "PO_EXPIRED_UNPAID",
                    "PO_INVALID"
                ],
                "type": "string"
            },
            "PaymentOptionsResponse": {
                "type": "object",
                "properties": {
                    "organizationFiscalCode": {
                        "type": "string"
                    },
                    "companyName": {
                        "type": "string"
                    },
                    "officeName": {
                        "type": "string"
                    },
                    "standin": {
                        "type": "boolean"
                    },
                    "paymentOptions": {
                        "type": "array",
                        "items": {
                            "$ref": "#/components/schemas/PaymentOption"
                        }
                    }
                }
            }
        },
        "securitySchemes": {
            "apiKeyHeader": {
                "type": "apiKey",
                "name": "Ocp-Apim-Subscription-Key",
                "in": "header"
            },
            "apiKeyQuery": {
                "type": "apiKey",
                "name": "subscription-key",
                "in": "query"
            }
        }
    },
    "security": [
        {
            "apiKeyHeader": []
        },
        {
            "apiKeyQuery": []
        }
    ],
    "tags": [
        {
            "name": "Payment Options",
            "description": "APIs to retrieve payment options"
        }
    ]
}